services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675
    environment:
      - RABBITMQ_DEFAULT_USER=gus
      - RABBITMQ_DEFAULT_PASS=gus

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend.dockerfile
    restart: always
    ports:
      - "5020:5020"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ./
      dockerfile: ./docker/worker.dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:5020
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  rabbitmq-data:
  rabbitmq-logs:
